# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7683224412e704e5a212ffe567330ab0e1bc98b24fc92301e163a36a997c5d06074b0b804c7b44ab3185c10e61d460dd99a5f82264610fe9eb856bc91885db4c

test:
  secret_key_base: 9a0ac6af8012ec7a937878ab1787663d02452faa44d71ecf0220164b429a4f7b3ff69777f651e15d82645b43910a35dbd3aea9bd15f5bea327440591856fc35c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
